### ISSUE TITLE
Issue with browserify + uglifyjs

### ISSUE THREAD

**Issue by cdevienne** [CalebMorris/react-moment-proptypes#12]
When I build my app with browserify, the output contains some "=>" operators, which are es6 specific.

They come from react-moment-proptypes, and to be more precise from:
https://github.com/CalebMorris/react-moment-proptypes/commit/a7c223a1c92c24cc5172d3ce5ef4de227a31baea#diff-168726dbe96b3ce427e7fedce31bb0bcR65
and https://github.com/CalebMorris/react-moment-proptypes/commit/a7c223a1c92c24cc5172d3ce5ef4de227a31baea#diff-168726dbe96b3ce427e7fedce31bb0bcR73

There are 2 things that react-moment-proptypes could do to avoid this issue :
1. Avoid using es6 in the distributed source (ie, get rid of two '=>')
2. Add the following in package.json, so that browserify knows how to transform the file :

``` json
   "browserify": {
     "transform": [["babelify", { "presets": ["es2015"] }]]
   },
```

I will provide a PR for 1, unless you prefer 2.

**Comment by lxe** [comment]
:+1: 

Thanks for the quick merge! Can you also `npm publish` this?

**Comment by CalebMorris** [comment]
Done and done. v1.1.1 up
Sorry for the delay, I merged from my phone, but didn't couldn't publish from work.
