### ISSUE TITLE
Throws error if prop is required

### ISSUE THREAD

**Issue by toblix** [CalebMorris/react-moment-proptypes#14]
The validator seems to throw an error if the prop is required, regardless of whether it is provided.

**Comment by CalebMorris** [comment]
Not sure when that happened, could have sworn I've used this with required props.
Thanks for submitting the issue.

**Comment by CalebMorris** [comment]
Version v1.1.2 published

**Comment by emragins** [comment]
Thanks.  This bug was causing headaches -- wish I saw that this had been fixed 5 days ago :D

**Comment by kirkstrobeck** [comment]
@CalebMorris it looks like this has resurfaced in 1.2.0
