### ISSUE TITLE
Undefined isRequired Prop Coverage Missing 

### ISSUE THREAD

**Issue by CalebMorris** [CalebMorris/react-moment-proptypes#26]
When adding warning to PropType for `isRequired` I noticed a behavior failure when using React `TestUtils.renderIntoDocument` vs manually testing in a browser.

May be either a failure of test setup, and failure of the test utilities suite or something else I'm missing and warrants further investigation as this behavior is now not automatically tested.

Example
```
<Blarg />
```
warns with value was `undefined` when required.

```
<Blarg foo={undefined} />`
```
throws no warning in test suite, but does in browser matching above behavior.

**Comment by ljharb** [comment]
You might want to use enzyme instead of TestUtils.

**Comment by CalebMorris** [comment]
https://github.com/airbnb/enzyme (for future shortcut)

Looks interesting, I'll have to try it out. Thanks.

**Comment by CalebMorris** [comment]
Tried a bunch of different things all with the same behavior.

- `'react-addons-test-utils'`.`createRenderer()`
- Enzyme
- JSDom on my own
- Using either JSX and `React.createElement`.

When passing `undefined` to a prop it doesn't throw a warning when `isRequired`.

Need to start peaking into the source if I can.

**Comment by CalebMorris** [comment]
Fixed from regression by unit tests.
Still need to find why it isn't testing correctly with helper renderers.
Possibly use headless Chromium, but no longer an issue.
