### ISSUE TITLE
Depencies outdated

### ISSUE THREAD

**Issue by CalebMorris** [CalebMorris/react-moment-proptypes#28]
Many of the dev-dependencies are out of date and may affect how the code behaves.
Possible problem ones are `React` for its test addons and `jsdom` for integration testing.

**Comment by CalebMorris** [comment]
I've created a set of browser runnable tests that can be viewed at [http://calebmorris.github.io/react-moment-proptypes-tests/](http://calebmorris.github.io/react-moment-proptypes-tests/).

This should reduce problems caused by dev dependencies being outdated.

**Comment by joelmeiller** [comment]
And _moment_ should be a peerDependency only (my npm library package bundles _moment_ because of the dependency)

**Comment by CalebMorris** [comment]
@joelmeiller , you can find a discussion in #46 about the place of `moment` as a peer or direct dependency.
This issue is specifically about updating the dev dependencies.
