### ISSUE TITLE
yarn check error

### ISSUE THREAD

**Issue by alexeikaratai** [CalebMorris/react-moment-proptypes#33]
error "react-moment-proptypes#moment" not installed
node 8.9.1
yarn 1.3.2
npm 5.5.1
moment 2.19.2
but if moment 2.19.1 all works good!

**Comment by CalebMorris** [comment]
Tested with node `8.9.1` and moment `2.19.2`.
Was unable to reproduce the problem.

Can you add more information on how you are able to get this to occur? I'm unfamiliar with `yarn` although it appears to just be a package-cache and not related to runtime. Could it be a corrupted cache?

[Test Branch](https://github.com/CalebMorris/react-moment-proptypes/tree/master_/33-package-error)
[Travis Run](https://travis-ci.org/CalebMorris/react-moment-proptypes/builds/307661632?utm_source=github_status&utm_medium=notification)

**Comment by alexeikaratai** [comment]
@CalebMorris reinit yarn and all remove, clear cache and then cleanup installing fix this =)
