### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by allan2** [CalebMorris/react-moment-proptypes#48]
Any plans for TS support?

**Comment by CalebMorris** [comment]
I haven't done a React app in Typescript as of yet.
Would you be looking for types support or something more?

**Comment by allan2** [comment]
Just types support would be great :)

**Comment by CalebMorris** [comment]
Alright. Looking into adding a declaration file.
Also trying to find some way of releasing the declaration without breaking existing Typescript applications.

**Comment by CalebMorris** [comment]
I've put up a pull request #49 and have tested against various React projects.
To prevent any sort compile problems that could come about from introducing this I'm going to release it in v1.8.0.

@allan2 would you mind pulling down the branch and testing? Confirm it works well enough with your use-case and doesn't cause any problems.

**Comment by tebatalla** [comment]
Is v 1.8.0 coming any time soon?

**Comment by CalebMorris** [comment]
Sorry, changed jobs and had some priority shift.
`v1.8.0` is now published with Typescript types file. I tested against a couple test projects, but if you find an error with the types, please reach out with a new issue.
